CREATE INDEX [IX_dp_Communications_Selection_ID_0419] ON [MinistryPlatform].[dbo].[dp_Communications] ([Selection_ID]) INCLUDE ([Communication_ID])
CREATE INDEX [IX_dp_Users_Domain_ID_User_GUID_0419] ON [MinistryPlatform].[dbo].[dp_Users] ([Domain_ID], [User_GUID])
CREATE INDEX [IX_dp_Communications_Domain_ID_Template_Active_Pertains_To_Page_ID_0419] ON [MinistryPlatform].[dbo].[dp_Communications] ([Domain_ID], [Template], [Active],[Pertains_To_Page_ID]) INCLUDE ([Communication_ID], [Subject])
CREATE INDEX [IX_dp_Audit_Detail_Audit_Item_ID_0419] ON [MinistryPlatform].[dbo].[dp_Audit_Detail] ([Audit_Item_ID]) INCLUDE ([Audit_Detail_ID], [Field_Name], [Field_Label], [Previous_Value], [New_Value], [Previous_ID], [New_ID])
CREATE INDEX [IX_dp_Communication_Messages_Contact_ID_0419] ON [MinistryPlatform].[dbo].[dp_Communication_Messages] ([Contact_ID]) INCLUDE ([Communication_Message_ID])
CREATE INDEX [IX_dp_Communications_To_Contact_0419] ON [MinistryPlatform].[dbo].[dp_Communications] ([To_Contact]) INCLUDE ([Communication_ID])
CREATE INDEX [IX_Donation_Distributions_Soft_Credit_Donor_Domain_ID_0419] ON [MinistryPlatform].[dbo].[Donation_Distributions] ([Soft_Credit_Donor], [Domain_ID]) INCLUDE ([Donation_Distribution_ID], [Donation_ID], [Amount], [Program_ID])
CREATE INDEX [IX_dp_Tasks_Assigned_User_ID_Completed_Domain_ID_0419] ON [MinistryPlatform].[dbo].[dp_Tasks] ([Assigned_User_ID], [Completed], [Domain_ID]) INCLUDE ([Task_ID], [Title], [Author_User_ID], [End_Date], [Description], [_Page_ID], [_Record_Description])
CREATE INDEX [IX_Events_Event_Type_ID_0419] ON [MinistryPlatform].[dbo].[Events] ([Event_Type_ID]) INCLUDE ([Event_ID], [Event_Title], [Program_ID], [Event_Start_Date], [Event_End_Date])
CREATE INDEX [IX_dp_Files_Record_ID_Domain_ID_0419] ON [MinistryPlatform].[dbo].[dp_Files] ([Record_ID],[Domain_ID])
CREATE INDEX [IX_Group_Participants_Group_Role_ID_End_Date_0419] ON [MinistryPlatform].[dbo].[Group_Participants] ([Group_Role_ID], [End_Date]) INCLUDE ([Group_ID], [Participant_ID])
CREATE INDEX [IX_Contacts_User_Account_Domain_ID_0419] ON [MinistryPlatform].[dbo].[Contacts] ([User_Account], [Domain_ID])
CREATE INDEX [IX_Donations_Donor_Account_ID_0419] ON [MinistryPlatform].[dbo].[Donations] ([Donor_Account_ID]) INCLUDE ([Donation_ID])
CREATE INDEX [IX_Donations_Transaction_Code_Domain_ID_0419] ON [MinistryPlatform].[dbo].[Donations] ([Transaction_Code], [Domain_ID])